[[Models]]
name = "Logistic"
function = "Logistic"
r_squared = 0.30506545305252075

[Models.params]
L = -1.7370988968615384
k = 1.0292682745992523
x0 = 6.863569892246658
y0 = 1.8991209751536968

[Models.bounds.min]
L = -inf
k = 0.0
x0 = -inf
y0 = -inf

[Models.bounds.max]
L = inf
k = inf
x0 = inf
y0 = inf

[[Models]]
name = "Quadratic"
function = "Quadratic"
r_squared = 0.28151410818099976

[Models.params]
a0 = 1.937022903873023
a1 = -0.023944678967493024
a2 = -0.012948736076671456

[Models.bounds.min]
a0 = -inf
a1 = -inf
a2 = -inf

[Models.bounds.max]
a0 = inf
a1 = inf
a2 = inf

[[Models]]
name = "Michaelis-Menten"
function = "MichaelisMentenSaturation"
r_squared = 0.26624566316604614

[Models.params]
v_max = -4416997.473327846
k = 24618764.812692255
y0 = 2.2225137850471546

[Models.bounds.min]
v_max = -inf
k = 0.0
y0 = -inf

[Models.bounds.max]
v_max = inf
k = inf
y0 = inf

[[Models]]
name = "Peak"
function = "PeakModel"
r_squared = 0.1724284291267395

[Models.params]
a = 2.479923569518766
b = 2.3872653421828676

[Models.bounds.min]
a = -inf
b = 0.0

[Models.bounds.max]
a = inf
b = inf

[[Models]]
name = "PeakÂ²"
function = "Peak2Model"
r_squared = 0.15114957094192505

[Models.params]
a = 2.0193057362031177
b = 1.4609780625641278

[Models.bounds.min]
a = -inf
b = 0.0

[Models.bounds.max]
a = inf
b = inf
